/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicLayoutRouteImport } from './routes/_public-layout'
import { Route as PrivateLayoutRouteImport } from './routes/_private-layout'
import { Route as PublicLayoutIndexRouteImport } from './routes/_public-layout.index'
import { Route as PublicLayoutProductsRouteImport } from './routes/_public-layout.products'
import { Route as PublicLayoutPoliciesRouteImport } from './routes/_public-layout.policies'
import { Route as PublicLayoutMyOrdersRouteImport } from './routes/_public-layout.my-orders'
import { Route as PublicLayoutCheckoutRouteImport } from './routes/_public-layout.checkout'
import { Route as PublicLayoutCartRouteImport } from './routes/_public-layout.cart'
import { Route as PrivateLayoutUsersRouteImport } from './routes/_private-layout.users'
import { Route as PrivateLayoutStatisticsRouteImport } from './routes/_private-layout.statistics'
import { Route as PrivateLayoutReturnFormsRouteImport } from './routes/_private-layout.return-forms'
import { Route as PrivateLayoutPenaltyFormsRouteImport } from './routes/_private-layout.penalty-forms'
import { Route as PrivateLayoutLoanFormsRouteImport } from './routes/_private-layout.loan-forms'
import { Route as PrivateLayoutInvoicesRouteImport } from './routes/_private-layout.invoices'
import { Route as PrivateLayoutInventoryRouteImport } from './routes/_private-layout.inventory'
import { Route as PrivateLayoutImagesGalleryRouteImport } from './routes/_private-layout.images-gallery'
import { Route as PrivateLayoutEquipmentPropsRouteImport } from './routes/_private-layout.equipment-props'
import { Route as PrivateLayoutEmployeesRouteImport } from './routes/_private-layout.employees'
import { Route as PrivateLayoutDashboardRouteImport } from './routes/_private-layout.dashboard'
import { Route as PrivateLayoutCustomersRouteImport } from './routes/_private-layout.customers'
import { Route as PrivateLayoutCostumesRouteImport } from './routes/_private-layout.costumes'
import { Route as PublicLayoutProductsIndexRouteImport } from './routes/_public-layout.products.index'
import { Route as PrivateLayoutReturnFormsIndexRouteImport } from './routes/_private-layout.return-forms.index'
import { Route as PrivateLayoutLoanFormsIndexRouteImport } from './routes/_private-layout.loan-forms.index'
import { Route as PrivateLayoutReturnFormsCreateRouteImport } from './routes/_private-layout.return-forms.create'
import { Route as PrivateLayoutLoanFormsCreateRouteImport } from './routes/_private-layout.loan-forms.create'
import { Route as PublicLayoutProductsTypeProductIdRouteImport } from './routes/_public-layout.products.$type.$productId'
import { Route as PrivateLayoutReturnFormsUpdateIdRouteImport } from './routes/_private-layout.return-forms.update.$id'
import { Route as PrivateLayoutLoanFormsUpdateIdRouteImport } from './routes/_private-layout.loan-forms.update.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutProductsRoute = PublicLayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutPoliciesRoute = PublicLayoutPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutMyOrdersRoute = PublicLayoutMyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCheckoutRoute = PublicLayoutCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCartRoute = PublicLayoutCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateLayoutUsersRoute = PrivateLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutStatisticsRoute = PrivateLayoutStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutReturnFormsRoute =
  PrivateLayoutReturnFormsRouteImport.update({
    id: '/return-forms',
    path: '/return-forms',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutPenaltyFormsRoute =
  PrivateLayoutPenaltyFormsRouteImport.update({
    id: '/penalty-forms',
    path: '/penalty-forms',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutLoanFormsRoute = PrivateLayoutLoanFormsRouteImport.update({
  id: '/loan-forms',
  path: '/loan-forms',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutInvoicesRoute = PrivateLayoutInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutInventoryRoute = PrivateLayoutInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutImagesGalleryRoute =
  PrivateLayoutImagesGalleryRouteImport.update({
    id: '/images-gallery',
    path: '/images-gallery',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutEquipmentPropsRoute =
  PrivateLayoutEquipmentPropsRouteImport.update({
    id: '/equipment-props',
    path: '/equipment-props',
    getParentRoute: () => PrivateLayoutRoute,
  } as any)
const PrivateLayoutEmployeesRoute = PrivateLayoutEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutDashboardRoute = PrivateLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCustomersRoute = PrivateLayoutCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateLayoutCostumesRoute = PrivateLayoutCostumesRouteImport.update({
  id: '/costumes',
  path: '/costumes',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PublicLayoutProductsIndexRoute =
  PublicLayoutProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicLayoutProductsRoute,
  } as any)
const PrivateLayoutReturnFormsIndexRoute =
  PrivateLayoutReturnFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateLayoutReturnFormsRoute,
  } as any)
const PrivateLayoutLoanFormsIndexRoute =
  PrivateLayoutLoanFormsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PrivateLayoutLoanFormsRoute,
  } as any)
const PrivateLayoutReturnFormsCreateRoute =
  PrivateLayoutReturnFormsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PrivateLayoutReturnFormsRoute,
  } as any)
const PrivateLayoutLoanFormsCreateRoute =
  PrivateLayoutLoanFormsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => PrivateLayoutLoanFormsRoute,
  } as any)
const PublicLayoutProductsTypeProductIdRoute =
  PublicLayoutProductsTypeProductIdRouteImport.update({
    id: '/$type/$productId',
    path: '/$type/$productId',
    getParentRoute: () => PublicLayoutProductsRoute,
  } as any)
const PrivateLayoutReturnFormsUpdateIdRoute =
  PrivateLayoutReturnFormsUpdateIdRouteImport.update({
    id: '/update/$id',
    path: '/update/$id',
    getParentRoute: () => PrivateLayoutReturnFormsRoute,
  } as any)
const PrivateLayoutLoanFormsUpdateIdRoute =
  PrivateLayoutLoanFormsUpdateIdRouteImport.update({
    id: '/update/$id',
    path: '/update/$id',
    getParentRoute: () => PrivateLayoutLoanFormsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof LoginRoute
  '/costumes': typeof PrivateLayoutCostumesRoute
  '/customers': typeof PrivateLayoutCustomersRoute
  '/dashboard': typeof PrivateLayoutDashboardRoute
  '/employees': typeof PrivateLayoutEmployeesRoute
  '/equipment-props': typeof PrivateLayoutEquipmentPropsRoute
  '/images-gallery': typeof PrivateLayoutImagesGalleryRoute
  '/inventory': typeof PrivateLayoutInventoryRoute
  '/invoices': typeof PrivateLayoutInvoicesRoute
  '/loan-forms': typeof PrivateLayoutLoanFormsRouteWithChildren
  '/penalty-forms': typeof PrivateLayoutPenaltyFormsRoute
  '/return-forms': typeof PrivateLayoutReturnFormsRouteWithChildren
  '/statistics': typeof PrivateLayoutStatisticsRoute
  '/users': typeof PrivateLayoutUsersRoute
  '/cart': typeof PublicLayoutCartRoute
  '/checkout': typeof PublicLayoutCheckoutRoute
  '/my-orders': typeof PublicLayoutMyOrdersRoute
  '/policies': typeof PublicLayoutPoliciesRoute
  '/products': typeof PublicLayoutProductsRouteWithChildren
  '/loan-forms/create': typeof PrivateLayoutLoanFormsCreateRoute
  '/return-forms/create': typeof PrivateLayoutReturnFormsCreateRoute
  '/loan-forms/': typeof PrivateLayoutLoanFormsIndexRoute
  '/return-forms/': typeof PrivateLayoutReturnFormsIndexRoute
  '/products/': typeof PublicLayoutProductsIndexRoute
  '/loan-forms/update/$id': typeof PrivateLayoutLoanFormsUpdateIdRoute
  '/return-forms/update/$id': typeof PrivateLayoutReturnFormsUpdateIdRoute
  '/products/$type/$productId': typeof PublicLayoutProductsTypeProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicLayoutIndexRoute
  '/login': typeof LoginRoute
  '/costumes': typeof PrivateLayoutCostumesRoute
  '/customers': typeof PrivateLayoutCustomersRoute
  '/dashboard': typeof PrivateLayoutDashboardRoute
  '/employees': typeof PrivateLayoutEmployeesRoute
  '/equipment-props': typeof PrivateLayoutEquipmentPropsRoute
  '/images-gallery': typeof PrivateLayoutImagesGalleryRoute
  '/inventory': typeof PrivateLayoutInventoryRoute
  '/invoices': typeof PrivateLayoutInvoicesRoute
  '/penalty-forms': typeof PrivateLayoutPenaltyFormsRoute
  '/statistics': typeof PrivateLayoutStatisticsRoute
  '/users': typeof PrivateLayoutUsersRoute
  '/cart': typeof PublicLayoutCartRoute
  '/checkout': typeof PublicLayoutCheckoutRoute
  '/my-orders': typeof PublicLayoutMyOrdersRoute
  '/policies': typeof PublicLayoutPoliciesRoute
  '/loan-forms/create': typeof PrivateLayoutLoanFormsCreateRoute
  '/return-forms/create': typeof PrivateLayoutReturnFormsCreateRoute
  '/loan-forms': typeof PrivateLayoutLoanFormsIndexRoute
  '/return-forms': typeof PrivateLayoutReturnFormsIndexRoute
  '/products': typeof PublicLayoutProductsIndexRoute
  '/loan-forms/update/$id': typeof PrivateLayoutLoanFormsUpdateIdRoute
  '/return-forms/update/$id': typeof PrivateLayoutReturnFormsUpdateIdRoute
  '/products/$type/$productId': typeof PublicLayoutProductsTypeProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private-layout': typeof PrivateLayoutRouteWithChildren
  '/_public-layout': typeof PublicLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_private-layout/costumes': typeof PrivateLayoutCostumesRoute
  '/_private-layout/customers': typeof PrivateLayoutCustomersRoute
  '/_private-layout/dashboard': typeof PrivateLayoutDashboardRoute
  '/_private-layout/employees': typeof PrivateLayoutEmployeesRoute
  '/_private-layout/equipment-props': typeof PrivateLayoutEquipmentPropsRoute
  '/_private-layout/images-gallery': typeof PrivateLayoutImagesGalleryRoute
  '/_private-layout/inventory': typeof PrivateLayoutInventoryRoute
  '/_private-layout/invoices': typeof PrivateLayoutInvoicesRoute
  '/_private-layout/loan-forms': typeof PrivateLayoutLoanFormsRouteWithChildren
  '/_private-layout/penalty-forms': typeof PrivateLayoutPenaltyFormsRoute
  '/_private-layout/return-forms': typeof PrivateLayoutReturnFormsRouteWithChildren
  '/_private-layout/statistics': typeof PrivateLayoutStatisticsRoute
  '/_private-layout/users': typeof PrivateLayoutUsersRoute
  '/_public-layout/cart': typeof PublicLayoutCartRoute
  '/_public-layout/checkout': typeof PublicLayoutCheckoutRoute
  '/_public-layout/my-orders': typeof PublicLayoutMyOrdersRoute
  '/_public-layout/policies': typeof PublicLayoutPoliciesRoute
  '/_public-layout/products': typeof PublicLayoutProductsRouteWithChildren
  '/_public-layout/': typeof PublicLayoutIndexRoute
  '/_private-layout/loan-forms/create': typeof PrivateLayoutLoanFormsCreateRoute
  '/_private-layout/return-forms/create': typeof PrivateLayoutReturnFormsCreateRoute
  '/_private-layout/loan-forms/': typeof PrivateLayoutLoanFormsIndexRoute
  '/_private-layout/return-forms/': typeof PrivateLayoutReturnFormsIndexRoute
  '/_public-layout/products/': typeof PublicLayoutProductsIndexRoute
  '/_private-layout/loan-forms/update/$id': typeof PrivateLayoutLoanFormsUpdateIdRoute
  '/_private-layout/return-forms/update/$id': typeof PrivateLayoutReturnFormsUpdateIdRoute
  '/_public-layout/products/$type/$productId': typeof PublicLayoutProductsTypeProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/costumes'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/equipment-props'
    | '/images-gallery'
    | '/inventory'
    | '/invoices'
    | '/loan-forms'
    | '/penalty-forms'
    | '/return-forms'
    | '/statistics'
    | '/users'
    | '/cart'
    | '/checkout'
    | '/my-orders'
    | '/policies'
    | '/products'
    | '/loan-forms/create'
    | '/return-forms/create'
    | '/loan-forms/'
    | '/return-forms/'
    | '/products/'
    | '/loan-forms/update/$id'
    | '/return-forms/update/$id'
    | '/products/$type/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/costumes'
    | '/customers'
    | '/dashboard'
    | '/employees'
    | '/equipment-props'
    | '/images-gallery'
    | '/inventory'
    | '/invoices'
    | '/penalty-forms'
    | '/statistics'
    | '/users'
    | '/cart'
    | '/checkout'
    | '/my-orders'
    | '/policies'
    | '/loan-forms/create'
    | '/return-forms/create'
    | '/loan-forms'
    | '/return-forms'
    | '/products'
    | '/loan-forms/update/$id'
    | '/return-forms/update/$id'
    | '/products/$type/$productId'
  id:
    | '__root__'
    | '/_private-layout'
    | '/_public-layout'
    | '/login'
    | '/_private-layout/costumes'
    | '/_private-layout/customers'
    | '/_private-layout/dashboard'
    | '/_private-layout/employees'
    | '/_private-layout/equipment-props'
    | '/_private-layout/images-gallery'
    | '/_private-layout/inventory'
    | '/_private-layout/invoices'
    | '/_private-layout/loan-forms'
    | '/_private-layout/penalty-forms'
    | '/_private-layout/return-forms'
    | '/_private-layout/statistics'
    | '/_private-layout/users'
    | '/_public-layout/cart'
    | '/_public-layout/checkout'
    | '/_public-layout/my-orders'
    | '/_public-layout/policies'
    | '/_public-layout/products'
    | '/_public-layout/'
    | '/_private-layout/loan-forms/create'
    | '/_private-layout/return-forms/create'
    | '/_private-layout/loan-forms/'
    | '/_private-layout/return-forms/'
    | '/_public-layout/products/'
    | '/_private-layout/loan-forms/update/$id'
    | '/_private-layout/return-forms/update/$id'
    | '/_public-layout/products/$type/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-layout': {
      id: '/_public-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private-layout': {
      id: '/_private-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public-layout/': {
      id: '/_public-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/products': {
      id: '/_public-layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof PublicLayoutProductsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/policies': {
      id: '/_public-layout/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PublicLayoutPoliciesRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/my-orders': {
      id: '/_public-layout/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof PublicLayoutMyOrdersRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/checkout': {
      id: '/_public-layout/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicLayoutCheckoutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public-layout/cart': {
      id: '/_public-layout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof PublicLayoutCartRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private-layout/users': {
      id: '/_private-layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateLayoutUsersRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/statistics': {
      id: '/_private-layout/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof PrivateLayoutStatisticsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/return-forms': {
      id: '/_private-layout/return-forms'
      path: '/return-forms'
      fullPath: '/return-forms'
      preLoaderRoute: typeof PrivateLayoutReturnFormsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/penalty-forms': {
      id: '/_private-layout/penalty-forms'
      path: '/penalty-forms'
      fullPath: '/penalty-forms'
      preLoaderRoute: typeof PrivateLayoutPenaltyFormsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/loan-forms': {
      id: '/_private-layout/loan-forms'
      path: '/loan-forms'
      fullPath: '/loan-forms'
      preLoaderRoute: typeof PrivateLayoutLoanFormsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/invoices': {
      id: '/_private-layout/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof PrivateLayoutInvoicesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/inventory': {
      id: '/_private-layout/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof PrivateLayoutInventoryRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/images-gallery': {
      id: '/_private-layout/images-gallery'
      path: '/images-gallery'
      fullPath: '/images-gallery'
      preLoaderRoute: typeof PrivateLayoutImagesGalleryRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/equipment-props': {
      id: '/_private-layout/equipment-props'
      path: '/equipment-props'
      fullPath: '/equipment-props'
      preLoaderRoute: typeof PrivateLayoutEquipmentPropsRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/employees': {
      id: '/_private-layout/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof PrivateLayoutEmployeesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/dashboard': {
      id: '/_private-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateLayoutDashboardRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/customers': {
      id: '/_private-layout/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof PrivateLayoutCustomersRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private-layout/costumes': {
      id: '/_private-layout/costumes'
      path: '/costumes'
      fullPath: '/costumes'
      preLoaderRoute: typeof PrivateLayoutCostumesRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public-layout/products/': {
      id: '/_public-layout/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof PublicLayoutProductsIndexRouteImport
      parentRoute: typeof PublicLayoutProductsRoute
    }
    '/_private-layout/return-forms/': {
      id: '/_private-layout/return-forms/'
      path: '/'
      fullPath: '/return-forms/'
      preLoaderRoute: typeof PrivateLayoutReturnFormsIndexRouteImport
      parentRoute: typeof PrivateLayoutReturnFormsRoute
    }
    '/_private-layout/loan-forms/': {
      id: '/_private-layout/loan-forms/'
      path: '/'
      fullPath: '/loan-forms/'
      preLoaderRoute: typeof PrivateLayoutLoanFormsIndexRouteImport
      parentRoute: typeof PrivateLayoutLoanFormsRoute
    }
    '/_private-layout/return-forms/create': {
      id: '/_private-layout/return-forms/create'
      path: '/create'
      fullPath: '/return-forms/create'
      preLoaderRoute: typeof PrivateLayoutReturnFormsCreateRouteImport
      parentRoute: typeof PrivateLayoutReturnFormsRoute
    }
    '/_private-layout/loan-forms/create': {
      id: '/_private-layout/loan-forms/create'
      path: '/create'
      fullPath: '/loan-forms/create'
      preLoaderRoute: typeof PrivateLayoutLoanFormsCreateRouteImport
      parentRoute: typeof PrivateLayoutLoanFormsRoute
    }
    '/_public-layout/products/$type/$productId': {
      id: '/_public-layout/products/$type/$productId'
      path: '/$type/$productId'
      fullPath: '/products/$type/$productId'
      preLoaderRoute: typeof PublicLayoutProductsTypeProductIdRouteImport
      parentRoute: typeof PublicLayoutProductsRoute
    }
    '/_private-layout/return-forms/update/$id': {
      id: '/_private-layout/return-forms/update/$id'
      path: '/update/$id'
      fullPath: '/return-forms/update/$id'
      preLoaderRoute: typeof PrivateLayoutReturnFormsUpdateIdRouteImport
      parentRoute: typeof PrivateLayoutReturnFormsRoute
    }
    '/_private-layout/loan-forms/update/$id': {
      id: '/_private-layout/loan-forms/update/$id'
      path: '/update/$id'
      fullPath: '/loan-forms/update/$id'
      preLoaderRoute: typeof PrivateLayoutLoanFormsUpdateIdRouteImport
      parentRoute: typeof PrivateLayoutLoanFormsRoute
    }
  }
}

interface PrivateLayoutLoanFormsRouteChildren {
  PrivateLayoutLoanFormsCreateRoute: typeof PrivateLayoutLoanFormsCreateRoute
  PrivateLayoutLoanFormsIndexRoute: typeof PrivateLayoutLoanFormsIndexRoute
  PrivateLayoutLoanFormsUpdateIdRoute: typeof PrivateLayoutLoanFormsUpdateIdRoute
}

const PrivateLayoutLoanFormsRouteChildren: PrivateLayoutLoanFormsRouteChildren =
  {
    PrivateLayoutLoanFormsCreateRoute: PrivateLayoutLoanFormsCreateRoute,
    PrivateLayoutLoanFormsIndexRoute: PrivateLayoutLoanFormsIndexRoute,
    PrivateLayoutLoanFormsUpdateIdRoute: PrivateLayoutLoanFormsUpdateIdRoute,
  }

const PrivateLayoutLoanFormsRouteWithChildren =
  PrivateLayoutLoanFormsRoute._addFileChildren(
    PrivateLayoutLoanFormsRouteChildren,
  )

interface PrivateLayoutReturnFormsRouteChildren {
  PrivateLayoutReturnFormsCreateRoute: typeof PrivateLayoutReturnFormsCreateRoute
  PrivateLayoutReturnFormsIndexRoute: typeof PrivateLayoutReturnFormsIndexRoute
  PrivateLayoutReturnFormsUpdateIdRoute: typeof PrivateLayoutReturnFormsUpdateIdRoute
}

const PrivateLayoutReturnFormsRouteChildren: PrivateLayoutReturnFormsRouteChildren =
  {
    PrivateLayoutReturnFormsCreateRoute: PrivateLayoutReturnFormsCreateRoute,
    PrivateLayoutReturnFormsIndexRoute: PrivateLayoutReturnFormsIndexRoute,
    PrivateLayoutReturnFormsUpdateIdRoute:
      PrivateLayoutReturnFormsUpdateIdRoute,
  }

const PrivateLayoutReturnFormsRouteWithChildren =
  PrivateLayoutReturnFormsRoute._addFileChildren(
    PrivateLayoutReturnFormsRouteChildren,
  )

interface PrivateLayoutRouteChildren {
  PrivateLayoutCostumesRoute: typeof PrivateLayoutCostumesRoute
  PrivateLayoutCustomersRoute: typeof PrivateLayoutCustomersRoute
  PrivateLayoutDashboardRoute: typeof PrivateLayoutDashboardRoute
  PrivateLayoutEmployeesRoute: typeof PrivateLayoutEmployeesRoute
  PrivateLayoutEquipmentPropsRoute: typeof PrivateLayoutEquipmentPropsRoute
  PrivateLayoutImagesGalleryRoute: typeof PrivateLayoutImagesGalleryRoute
  PrivateLayoutInventoryRoute: typeof PrivateLayoutInventoryRoute
  PrivateLayoutInvoicesRoute: typeof PrivateLayoutInvoicesRoute
  PrivateLayoutLoanFormsRoute: typeof PrivateLayoutLoanFormsRouteWithChildren
  PrivateLayoutPenaltyFormsRoute: typeof PrivateLayoutPenaltyFormsRoute
  PrivateLayoutReturnFormsRoute: typeof PrivateLayoutReturnFormsRouteWithChildren
  PrivateLayoutStatisticsRoute: typeof PrivateLayoutStatisticsRoute
  PrivateLayoutUsersRoute: typeof PrivateLayoutUsersRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateLayoutCostumesRoute: PrivateLayoutCostumesRoute,
  PrivateLayoutCustomersRoute: PrivateLayoutCustomersRoute,
  PrivateLayoutDashboardRoute: PrivateLayoutDashboardRoute,
  PrivateLayoutEmployeesRoute: PrivateLayoutEmployeesRoute,
  PrivateLayoutEquipmentPropsRoute: PrivateLayoutEquipmentPropsRoute,
  PrivateLayoutImagesGalleryRoute: PrivateLayoutImagesGalleryRoute,
  PrivateLayoutInventoryRoute: PrivateLayoutInventoryRoute,
  PrivateLayoutInvoicesRoute: PrivateLayoutInvoicesRoute,
  PrivateLayoutLoanFormsRoute: PrivateLayoutLoanFormsRouteWithChildren,
  PrivateLayoutPenaltyFormsRoute: PrivateLayoutPenaltyFormsRoute,
  PrivateLayoutReturnFormsRoute: PrivateLayoutReturnFormsRouteWithChildren,
  PrivateLayoutStatisticsRoute: PrivateLayoutStatisticsRoute,
  PrivateLayoutUsersRoute: PrivateLayoutUsersRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutProductsRouteChildren {
  PublicLayoutProductsIndexRoute: typeof PublicLayoutProductsIndexRoute
  PublicLayoutProductsTypeProductIdRoute: typeof PublicLayoutProductsTypeProductIdRoute
}

const PublicLayoutProductsRouteChildren: PublicLayoutProductsRouteChildren = {
  PublicLayoutProductsIndexRoute: PublicLayoutProductsIndexRoute,
  PublicLayoutProductsTypeProductIdRoute:
    PublicLayoutProductsTypeProductIdRoute,
}

const PublicLayoutProductsRouteWithChildren =
  PublicLayoutProductsRoute._addFileChildren(PublicLayoutProductsRouteChildren)

interface PublicLayoutRouteChildren {
  PublicLayoutCartRoute: typeof PublicLayoutCartRoute
  PublicLayoutCheckoutRoute: typeof PublicLayoutCheckoutRoute
  PublicLayoutMyOrdersRoute: typeof PublicLayoutMyOrdersRoute
  PublicLayoutPoliciesRoute: typeof PublicLayoutPoliciesRoute
  PublicLayoutProductsRoute: typeof PublicLayoutProductsRouteWithChildren
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutCartRoute: PublicLayoutCartRoute,
  PublicLayoutCheckoutRoute: PublicLayoutCheckoutRoute,
  PublicLayoutMyOrdersRoute: PublicLayoutMyOrdersRoute,
  PublicLayoutPoliciesRoute: PublicLayoutPoliciesRoute,
  PublicLayoutProductsRoute: PublicLayoutProductsRouteWithChildren,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
